-- MySQL Script generated by MySQL Workbench
-- Sat Jul 27 20:54:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sensor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NULL,
  `Host` VARCHAR(255) NOT NULL,
  `Interval` INT NOT NULL,
  `Status` VARCHAR(128) NULL,
  `StatusTime` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TempHumData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TempHumData` (
  `Time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Temperature` FLOAT NULL,
  `Humidity` FLOAT NULL,
  `SensorID` INT NOT NULL,
  INDEX `SensorIDd_idx` (`SensorID` ASC) VISIBLE,
  CONSTRAINT `SensorIDd`
    FOREIGN KEY (`SensorID`)
    REFERENCES `mydb`.`Sensor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
