-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 22:17:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sensor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NULL,
  `Status` VARCHAR(128) NULL,
  `LastStatus` DATETIME NULL,
  `APIKey` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `APIKey_UNIQUE` (`APIKey` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Data` (
  `Time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SensorID` INT NOT NULL,
  `Temperature` FLOAT NULL,
  `Humidity` FLOAT NULL,
  INDEX `SensorIDd_idx` (`SensorID` ASC),
  CONSTRAINT `SensorIDd`
    FOREIGN KEY (`SensorID`)
    REFERENCES `mydb`.`Sensor` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SensorConfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SensorConfig` (
  `SensorID` INT NOT NULL,
  `Interval` INT NULL,
  `Debug` TINYINT(1) NOT NULL DEFAULT 0,
  `DebugHost` VARCHAR(128) NULL,
  PRIMARY KEY (`SensorID`),
  UNIQUE INDEX `SensorID_UNIQUE` (`SensorID` ASC),
  CONSTRAINT `SensorIDsc`
    FOREIGN KEY (`SensorID`)
    REFERENCES `mydb`.`Sensor` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Errors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Errors` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Error` VARCHAR(4096) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
